### ISSUE TITLE
[Question] About plasma

### ISSUE THREAD

**Issue by varlesh** [phobi4n/Huen#2]
Hi, good work :)
You know plasma tools, please tell me it's possible ignore color for text on `panel-background` widget?
I mean darker style - dark panel (i know it's widget too, but nonetheless) and light widgets.
Maybe CSS or another way?
For example:
![image](https://user-images.githubusercontent.com/8083855/30211616-cd1d2f2e-94b2-11e7-8d8e-bf4ef3f4122b.png)

**Comment by varlesh** [comment]
On plasma:
![image](https://user-images.githubusercontent.com/8083855/30212150-b0878628-94b4-11e7-8efe-6b3d64d65f45.png)
See, text class color on panel-background  used on other widgets too... Possible ignore this text color on panel widget? Or other way change this?

**Comment by phobi4n** [comment]
Apologies for late reply, my notifications were being sent to a defunct email account. I find the single use of text color to be quite limiting and asked on the Plasma IRC channel about it but no-one was willing to change it. I also asked about CSS styling which I liked using for Be::Shell but again, no change was considered.
