### ISSUE TITLE
Allow for local installation in user home

### ISSUE THREAD

**Issue by kupiqu** [phobi4n/Huen#3]
Some people including me don't like to run third scripts with sudo and in plasma there is no need for it. Everything should be able to be installed in plasma folders inside the user home directory.

It would be nice to have an option for local installation.

Thanks

**Comment by phobi4n** [comment]
Apologies for long delay. Didn't realise notifications were being sent to a defunct email account. 

Latest update now installs to user's home.

**Comment by kupiqu** [comment]
Thanks for your work on this, but unfortunately the install script is still asking me to run it as sudo.

**Comment by phobi4n** [comment]
Sorry, fixed now.

**Comment by kupiqu** [comment]
Thank you

**Comment by kupiqu** [comment]
I think the uninstall script also needs an update.

**Comment by kupiqu** [comment]
The code compiles when I run the install script but the theme doesn't appear in settings. Shouldn't the theme be installed in `~/.local/share/plasma/desktoptheme/` instead of in `~/.local/share/` ?

**Comment by phobi4n** [comment]
The uninstaller is updated. The base theme should be in ~/.local/share/huen which is then copied by the binary to ~/.local/share/plasma/desktoptheme. This is because the binary used to modify the SVG elements before writing them to the Plasma desktop theme directory and I want to retain this option.

The .desktop file is written to ~/.local/share/applications as defined by XDG_DATA_HOME=~/.local/share. Maybe your setup is different so I'd need more information before knowing why the menu entry doesn't show.

**Comment by kupiqu** [comment]
Thanks for updating the uninstall script.

I see, I guess then the issue why the final theme is not copied at `~/.local/share/plasma/desktoptheme` comes from the following error I'm having when manually running the binary:

```
terminate called after throwing an instance of 'Magick::ErrorBlob'
  what():  Magick: unable to open image `wallpaper_path/wallpaper.jpeg': No such file or directory @ error/blob.c/OpenBlob/2712
Aborted
```

It's curious, it's like the binary misses `/home/` and the first letter of my username in `wallpaper_path`, so the wallpaper image is not found. Do you know what could be going wrong here?

**Comment by phobi4n** [comment]
I have a good idea what might be happening but need more information to confirm. Pull the latest update, install and run Huen in a term; it should now print 5 lines of information. Would you copy them for me into your next reply.

**Comment by kupiqu** [comment]
This is the output (just replaced `my_username` by `username`):

```
01. Huen data directory:  "/home/username/.local/share/huen"
02. Plasma config file:  "/home/username/.config/plasma-org.kde.plasma.desktop-appletsrc"
03. Wallpaper path from config file:  "sername/Imatges/Wallpapers/Seasons/hd-wallpapers-free-autumn-desktop-background.jpeg"
04. Wallpaper path from ImageRGB:  "sername/Imatges/Wallpapers/Seasons/hd-wallpapers-free-autumn-desktop-background.jpeg"
terminate called after throwing an instance of 'Magick::ErrorBlob'
  what():  Magick: unable to open image `sername/Imatges/Wallpapers/Seasons/hd-wallpapers-free-autumn-desktop-background.jpeg': No such file or directory @ error/blob.c/OpenBlob/2712
05. Wallpaper path as Std::String: sername/Imatges/Wallpapers/Seasons/hd-wallpapers-free-autumn-desktop-background.jpegAborted
```

**Comment by phobi4n** [comment]
Well I need to know exactly the output because the error is obviously an extended character. By replacing the paths, I still can't see what the issue is. If you really need to conceal your login name, add another user and install Huen there so I can see full paths as printed by Huen.

**Comment by kupiqu** [comment]
There is nothing really special in my username, the missing letter is a "j"

**Comment by phobi4n** [comment]
At the very least I will need a copy of ~/.config/plasma-org.kde.plasma.desktop-appletsrc  There is obviously a character or something else which is not being read correctly.

**Comment by kupiqu** [comment]
I'm pretty sure the problem is not an extended character (don't  have any). However, I see three different Wallpaper sections in my ~/.config/plasma-org.kde.plasma.desktop-appletsrc file:

```
[Containments][100][Wallpaper][org.kde.image][General]
FillMode=6
Image=/home/username/Imatges/Wallpapers/Seasons/hd-wallpapers-free-autumn-desktop-background.jpeg
```

```
[Containments][200][Wallpaper][org.kde.image][General]
FillMode=2
Image=file:///home/username/Imatges/Wallpapers/pedra.jpg
```

```
[Containments][206][Wallpaper][org.kde.image][General]
Image=/home/username/Imatges/Wallpapers/Seasons/hd-wallpapers-free-autumn-desktop-background.jpeg
```

I guess they relate to an external monitor (projector) and a different activity.

The second one is my current wallpaper, however, huen binary gets a different one (I guess the first one).

Also, note that two of them miss `file://`

I will manually edit the file to see if I can get huen binary work, and will let you know

**Comment by kupiqu** [comment]
Ok, this is what is going on:

1. The problem comes from the missing` file://`
2. Huen should not use the first Wallpaper, but the one that corresponds to the activity that is active

Both issues can be workarounded by moving the proper wallpaper to appear first and adding the missing "file://" part

**Comment by kupiqu** [comment]
Point 1 above, should be easy to fix. I'm not sure how easy is to fix point 2 :/

**Comment by phobi4n** [comment]
OK. Worked out how to choose wallpaper by current activity, needs a bit of code so will do it on the weekend. Not sure what's going on with the missing Image=file://... (all of mine have it) but will implement better parsing to retrieve the correct filename regardless. Again, give me a day or two.

**Comment by kupiqu** [comment]
Sure. Thank you very much!

Would there be a way to use current desktoptheme and run huen on top of it?

**Comment by phobi4n** [comment]
I think only Breeze (default) has SVG elements which all have the "Class" tags and style definitions that follow a colour scheme. The problem is designing the theme so that it will work with bright/dark and low/high contrast schemes which is why I've kept it simple. Happy to listen to any ideas tho.

**Comment by kupiqu** [comment]
I see, that makes sense. Thanks

**Comment by phobi4n** [comment]
Updated. I've left the debug statements in so try running it in a term again.

**Comment by kupiqu** [comment]
It works great! :)

**Comment by phobi4n** [comment]
Very good. Any changes to the theme itself you'd suggest?

**Comment by kupiqu** [comment]
Well, I like the Adapta theme quite a lot, but based on what we talked about, I guess it's not possible to integrate together Huen and the Adapta theme.

Other than that I'm very happy with Huen, thank you! :)

**Comment by phobi4n** [comment]
Thanks for your help. Closing this issue.

**Comment by kupiqu** [comment]
Thanks to you! :)

Should the debug info be cleared from the Huen binary?

**Comment by phobi4n** [comment]
It will be. Want to make changes to the theme then will make a new release tomorrow or Monday.

**Comment by phobi4n** [comment]
In the process of re-writing the theme so you might want to take a look. Added more code to help with dark colours.

**Comment by kupiqu** [comment]
Cool!

**Comment by phobi4n** [comment]
Finally, the new release. Just about every pixel's be re-designed. Watch this https://youtu.be/xvJ1-V_WJpM

**Comment by kupiqu** [comment]
Very nice!!

I think we can close the issue now :)
